In [1]:
import pandas as pd

In [10]:
df = pd.read_csv("HousePricePrediction.csv")

In [18]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            2919 non-null   int64
 1   MSSubClass    2919 non-null   int64
 2   MSZoning      2915 non-null   object
 3   LotArea       2919 non-null   int64
 4   LotConfig     2919 non-null   object
 5   BldgType      2919 non-null   object
 6   OverallCond   2919 non-null   int64
 7   YearBuilt     2919 non-null   int64
 8   YearRemodAdd  2919 non-null   int64
 9   Exterior1st   2918 non-null   object
 10  BsmtFinSF2    2918 non-null   float64
 11  TotalBsmtSF   2918 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(6), object(4)
memory usage: 296.6+ KB

In [29]:
df.describe()

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice
count,2913.000000,2913.000000,2913.000000,2913.000000,2913.000000,2913.000000,2913.000000,2913.000000
mean,57.190182,10137.665980,5.566770,1971.391349,1984.314452,49.667353,1052.805012,180921.195890
std,42.538067,7832.598853,1.108977,30.258751,20.864950,169.338330,439.688510,56232.174632
min,20.000000,1300.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,34900.000000
25%,20.000000,7476.000000,5.000000,1954.000000,1965.000000,0.000000,793.000000,163000.000000
50%,50.000000,9450.000000,5.000000,1973.000000,1993.000000,0.000000,990.000000,180921.195890
75%,70.000000,11553.000000,6.000000,2001.000000,2004.000000,0.000000,1302.000000,180921.195890
max,190.000000,215245.000000,9.000000,2010.000000,2010.000000,1526.000000,6110.000000,755000.000000

In [27]:
df['SalePrice']=df['SalePrice'].fillna(df['SalePrice'].mean())
df = df.dropna()

In [31]:
df.isna().sum()

MSSubClass      0
MSZoning        0
LotArea         0
LotConfig       0
BldgType        0
OverallCond     0
YearBuilt       0
YearRemodAdd    0
Exterior1st     0
BsmtFinSF2      0
TotalBsmtSF     0
SalePrice       0
dtype: int64

In [32]:
df.head()

,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0

In [33]:
cols = ['MSZoning', 'LotConfig', 'BldgType', 'Exterior1st']
df = pd.get_dummies(df, columns=cols, drop_first=True)

In [38]:
from sklearn.model_selection import train_test_split

X = df.drop(['SalePrice'],axis=1)
Y=  df['SalePrice']

X_train,X_test,Y_train,Y_test = train_test_split(
    X,Y, test_size=0.2,random_state=0
)

In [40]:
X_train.head()

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,MSZoning_FV,MSZoning_RH,MSZoning_RL,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
1453,20,17217,5,2006,2006,0.0,1140.0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
2021,20,19508,5,1974,1974,0.0,1430.0,False,False,True,...,False,True,False,False,False,False,False,False,False,False
188,90,7018,5,1979,1979,0.0,1086.0,False,False,True,...,False,False,False,False,True,False,False,False,False,False
1273,80,11512,7,1959,2006,0.0,1019.0,False,False,True,...,False,False,False,False,True,False,False,False,False,False
1960,20,7560,5,1971,1971,613.0,864.0,False,False,True,...,False,False,False,True,False,False,False,False,False,False

In [42]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,Y_train)

LinearRegression()

In [43]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.metrics import mean_absolute_percentage_error
import numpy as np

In [52]:
Y_test

1728    180921.19589
2689    180921.19589
1151    149900.00000
2762    180921.19589
1180    250000.00000
            ...
1840    180921.19589
776     221500.00000
1519    180921.19589
1359    315000.00000
563     185000.00000
Name: SalePrice, Length: 583, dtype: float64

In [48]:
y_pred = model.predict(X_test)
y_pred

array([191650.15923448, 256694.21204008, 172701.86041707, 178271.40635751,
       206419.73613527, 197732.89101835, 122841.48375806, 157878.58934739,
       191291.77887933, 204804.03308353, 150243.64027563, 219384.08152954,
       175255.50575307, 146897.11420032, 199206.87801954, 140385.69033295,
       168183.44447516, 163859.73646193, 199489.97467244, 197189.64221704,
       196128.98519652, 133933.9044786 , 213384.66385957, 171491.85738481,
       134813.81633664, 155413.33744835, 147306.70226194, 172544.46498721,
       162993.16873965, 149133.18652125, 165985.90539425, 190830.50970741,
       163121.19310168, 194180.02729621, 173858.91795552, 196437.34882538,
       141050.11569807, 164048.62478895, 170097.87353521, 168791.86980325,
       213867.76779934, 227566.00767484, 225968.6660771 , 141556.62431201,
       200123.25857304, 221255.82922142, 219628.0509285 , 112066.64524962,
       170881.54038786, 195695.22225926, 199297.32301991, 194250.64094596,
       125567.5270662 , 153150.46411961, 197129.20194131, 152353.39846161,
       135830.20477893, 222158.33887991, 182830.5698671 , 199591.81857295,
       206995.28102923, 167071.6365769 , 132145.03008325, 165280.23809107,
       191581.54045588, 193196.65980594, 103591.35181865, 152442.19956667,
       159762.61508729, 178125.05210997, 161177.87763617, 202334.03218544,
       182622.91838593, 210320.34244289, 178795.69789939, 152790.32828778,
       196562.57185731, 188656.29977069, 108861.32389705, 205452.4118858 ,
       146418.04130528, 185508.05878859, 200085.66470105, 173664.15115611,
       152563.57845667, 167130.72701883, 156085.45243031, 205144.53831838,
       156262.2745535 , 166136.79845492, 170341.99178056, 202329.07708252,
       178583.46245341, 154552.01748482, 182038.45296562, 140041.69857018,
       166159.47680368, 159380.27637839, 180167.41246586, 130669.94938674,
       158226.58894704, 161846.4400881 , 183023.44636532, 197549.80792774,
       147124.96528779, 207299.53229971, 200496.89994813, 203173.63119264,
       136094.1807554 , 189217.84564845, 125391.7640702 , 240341.69712077,
       189002.73523215, 203512.92334777, 195101.9053968 , 182486.30719165,
       214773.27902033, 162974.20081412, 223397.4390014 , 157571.78490548,
       249563.70910754, 236224.16581948, 188980.2377198 , 156848.38730685,
       164643.13017448, 212348.10352044, 179568.16162026, 183563.71858062,
       162040.75641552, 174208.90619854, 138164.41005464, 180053.61341676,
       219327.37215153, 183653.16593677, 142553.6130701 , 159921.46618762,
       216942.14453575, 153915.58503433, 180529.34303608, 224214.08382836,
       140570.48811537, 184988.42070619, 189369.51151102, 184105.93719487,
       190463.08648833, 186086.66449492, 204289.10461769, 173081.36360414,
       122388.91322082, 153238.8827715 , 206588.82104785, 193089.81627246,
       162612.7088665 , 156210.93746848, 134697.88704499, 129352.58363822,
       152894.00465783, 134080.1714976 , 202690.24754149, 195507.125394  ,
       163581.29424809, 143358.34582482, 194462.55540589, 163917.81143593,
       166293.10329641, 214040.98938066, 211574.68273738, 191924.47306022,
       218346.68932357, 192370.65283059, 191839.4488424 , 140982.74331061,
       170986.91658594, 228467.4562873 , 189795.66824961, 171380.98149269,
       167204.51996726, 195920.40314583, 222685.06032403, 211418.99874296,
       139003.196343  , 183425.22379166, 198388.68215031, 164097.59907819,
       207873.45493517, 212662.26482356, 193415.1317507 , 224259.2669964 ,
       124529.11386477, 183742.48459046, 162835.16412623, 150047.84524216,
       185121.53680951, 158437.30001561, 165040.56655029, 215374.3944688 ,
       246793.49156565, 183091.87821116, 152634.09263721, 145412.95138878,
       206240.84968936, 177877.83321642, 198176.94681377, 178169.1063031 ,
       171750.44278289, 151088.79987455, 186306.32479273, 206520.86513188,
       164877.50812912, 127726.22291576, 150686.49081358, 181695.11905209,
       212179.86581805, 163103.31171669, 152990.85121135, 180660.39432206,
       169464.79092849, 177441.17468367, 191677.84762687, 197762.89509114,
       140196.22437798, 165031.30577442, 163103.0482237 , 160217.99067022,
       161630.69688484, 228686.06017951, 201734.49295909, 156776.61383726,
       220764.25844639, 172657.94975284, 157892.28566168, 130188.03823272,
       181890.9663808 , 162193.22369803, 148362.85636308, 204032.6986039 ,
       140771.32914958, 197745.59464927, 202216.4847224 , 154584.86958344,
       192980.2483389 , 189433.1411219 , 163974.09038389, 128151.6150645 ,
       165471.7852081 , 154009.44986318, 114276.38518658, 191467.14998444,
       201766.35991297, 243815.22636918, 197201.29612013, 167978.07836354,
       149593.04998124, 235215.01178878, 209517.57924122, 157168.11391902,
       200963.07577616, 224670.00232522, 199702.57758213, 196093.20891356,
       184286.00314884, 201678.13110549, 168866.40455299, 192032.40886443,
       228268.61200492, 167734.62711179, 137099.84842235, 162448.66612707,
       214718.91834374, 125018.18748767, 109055.48638791, 228389.08792348,
       202622.64399625, 157986.45349265, 135999.36969401, 245970.18690599,
       249845.01775737, 169861.56360205, 187794.0844776 , 156985.37589436,
       157691.99793424, 189357.63616315, 202300.30906458, 208686.87567854,
       161557.81725841, 186342.19636851, 277953.80056097, 179682.44249769,
       217078.93371855, 178528.39054036, 141387.32550343, 209110.24994302,
       220006.04936558, 170166.16781381, 190120.3202604 , 157011.61608481,
       210385.07824685, 189335.8388503 , 200391.76883881, 213929.83229419,
       162650.3261084 , 115283.60135915, 211925.01942293, 180839.69874967,
       291856.58431674, 184922.71917659, 150475.23714941, 217765.01443414,
       152525.73762179, 186884.12503031, 179577.14414355, 192476.57496545,
       151020.19175113, 217736.2017309 , 165335.87466962, 159383.85992064,
       196827.74066615, 164424.92883679, 242181.5109977 , 154617.68708259,
       194373.53999969, 135000.9787347 , 187072.03734778, 107214.63585346,
       206974.7294392 , 197350.23444531, 208493.99020681, 133273.95641865,
       194771.94291732, 164041.51012583, 159939.90216636, 266639.92753123,
       152297.95485235, 223931.9761604 , 222080.19837819, 168237.58249013,
       213650.31403729, 169815.08598669, 201238.18626997, 196477.95456759,
       190584.67394625, 125250.7313308 , 227968.25089577, 152567.07340144,
       160573.22978706, 163896.735831  , 153367.97438252, 136918.0768587 ,
       209967.01768203, 176282.38763741, 194370.01118432, 187669.6725847 ,
       225903.28599189, 133781.84545028, 200243.70888713, 177422.03343017,
       172989.17397813, 150838.46729041, 231289.43158383, 208124.109234  ,
       221275.57230878, 199603.37870735, 151767.01879375, 190894.97635623,
       143551.53699387, 217139.83814417, 226955.46289122, 203998.00543363,
       155633.01612873, 191633.40436021, 204342.64142371, 192368.22665126,
       163754.02503985, 174021.77692558, 243706.08096336, 156725.04372106,
       167041.89355352, 214685.1748546 , 144895.55674014, 209313.62190062,
       163146.67410132, 161771.234087  , 154664.05356787, 171655.10772044,
       149555.1804394 , 198174.06070772, 200111.90335822, 197824.25295637,
       205973.2032717 , 179052.87849808, 195206.82566327, 201548.27628392,
       214413.91267213, 217695.35791504, 198118.97722547, 145419.62391366,
       167661.80566762, 145150.327857  , 197843.67050141, 232420.83897517,
       228932.64661106, 181626.382932  , 197042.42000747, 214470.37558414,
       174353.19765831, 197535.49354661, 178689.43024093, 168069.84823825,
       174460.32028928, 161464.40422562, 234350.20175697, 201280.89094348,
       187522.91972751, 152371.90750043, 145640.66049919, 120263.66982783,
       211866.82664087, 160761.93890185, 163968.84110086, 168770.11405902,
       183747.1486932 , 176992.63466184, 153794.10854779, 184052.15279831,
       191768.51219328, 209682.65347589, 161125.30944926, 210090.50526249,
       215470.07799218, 153495.13973922, 165551.74492479, 202057.10277663,
       172184.48145825, 149617.58767225, 139929.10088472, 179284.78777547,
       198407.40550871, 165425.35995843, 128209.16659528, 135701.62307083,
       183420.46855714, 187025.80284937, 167474.70625205, 179196.37272046,
       139251.60413747, 227418.60176899, 171627.98535911, 166289.52666189,
       186638.17127031, 142600.94776957, 201580.93561705, 200192.44573651,
       170082.25003434, 194505.01077074, 145595.40180284, 195878.91633476,
       147861.29174847, 147329.06016297, 153318.39868591, 174818.05996929,
       183377.258809  , 199042.74360384, 219593.47355584, 206456.60283519,
       175016.14153767, 158821.3300455 , 219803.60803862, 269553.83208139,
       150766.9001694 , 153125.92510773, 185376.42081139, 226013.02441779,
       115570.66258354, 183639.92184371, 196954.95505776, 193627.39231335,
       259957.70057709, 149594.52708001, 189973.9672442 , 183113.36610217,
       212063.08764871, 221204.93939473, 167845.22973508, 200958.19846304,
       246893.40917657, 231133.50981015, 171498.56904499, 153512.11119461,
       213751.01251444, 198547.49663447, 167935.69047256, 193154.04942848,
       134654.55719417, 196741.48404901, 185922.03902849, 227195.52318948,
       184001.77126074, 147933.82642164, 156857.28218923, 160645.84320327,
       158138.57932742, 187173.20783565,  97671.42341417, 218282.58035155,
       193387.77206032, 206188.30332299, 200846.96849104, 227789.25563364,
       123621.76197759, 197691.88284033, 209941.21451114, 200608.56266016,
       208310.58821439, 201973.02781632, 204370.92669917, 211452.39083897,
       178697.51245786, 129454.13330637, 199534.91725978, 174038.35075141,
       203429.3475993 , 214759.28854557, 201334.97059272, 150222.81481052,
       234092.68252893, 165717.80739965, 161344.52237291, 192013.87587522,
       213751.70058395, 175590.51698923, 146271.83378554, 124017.0204682 ,
       205483.06711297, 175728.28244497, 182824.49818821, 216873.64501293,
       158830.29175726, 166528.17251336, 161526.26797488, 193569.76107649,
       152435.51796907, 191824.98161746, 203366.63090272, 178666.12586971,
       152510.99784763, 207219.01682496, 187658.02790858, 140361.7074512 ,
       189903.38566049, 194251.08026036, 146480.40764895, 175955.19708697,
       158995.89513212, 140331.28428197, 213327.09841872, 158318.58409243,
       176701.49361092, 191927.12971954, 169858.19288018, 224079.90237519,
       167074.16533938, 170130.51855398, 115775.09984379, 221552.77665547,
       194319.56180773, 171600.61447218, 220920.5004128 , 204553.03927472,
       134709.7289432 , 125301.90266127, 212075.4436422 , 203524.73530383,
       173415.20564912, 213076.80929429, 180816.47116083, 202257.6785005 ,
       189445.30482474, 126858.84831435, 168536.34337095, 216034.91618087,
       157497.77526479, 226436.30256944, 178107.07759146])

In [50]:
print("R2 Score:", r2_score(Y_test, y_pred))
print("MAE:", mean_absolute_error(Y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(Y_test, y_pred)))
print(mean_absolute_percentage_error(Y_test, y_pred))

R2 Score: 0.37414217961383156
MAE: 30829.93666432242
RMSE: 41138.558702301765
0.18742025463428386

In [54]:
# Feature Scaling - to try & improve baseline performance
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = LinearRegression()
model.fit(X_train_scaled, Y_train)

y_pred = model.predict(X_test_scaled)

print("R2 Score:", r2_score(Y_test, y_pred))
print("MAE:", mean_absolute_error(Y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(Y_test, y_pred)))
print(mean_absolute_percentage_error(Y_test, y_pred))

# To get better results we can try some other regression model 
# & also use techniques like Bagging & Boosting (will cover later).

R2 Score: 0.3741421796138532
MAE: 30829.93666432187
RMSE: 41138.55870230105
0.18742025463427797