In [17]:
import pandas as pd

In [18]:
df = pd.read_csv("Iris_dataset.csv")
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [19]:
df.nunique()

Id               150
SepalLengthCm     35
SepalWidthCm      23
PetalLengthCm     43
PetalWidthCm      22
Species            3
dtype: int64

In [26]:
# convert 3 species into 0, 1, 2
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Species'] = le.fit_transform(df['Species'])
df.sample(5)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
15    16            5.7           4.4            1.5           0.4        0
36    37            5.5           3.5            1.3           0.2        0
101  102            5.8           2.7            5.1           1.9        2
51    52            6.4           3.2            4.5           1.5        1
129  130            7.2           3.0            5.8           1.6        2

In [27]:

X = df.drop('Species', axis=1)
y = df['Species']


from sklearn.model_selection import train_test_split
x_train ,x_test , y_train , y_test = train_test_split(
    X ,y, test_size = 0.2 ,random_state = 42
)