In [7]:
from sklearn.svm import SVC
from sklearn import datasets
import pandas as pd 
from sklearn.model_selection import train_test_split

In [9]:
df = datasets.load_iris(as_frame=True).frame

In [10]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [12]:
df.isnull().sum()
df.shape

(150, 5)

In [18]:
X = df.drop("target" , axis =1)
y = df["target"]

In [20]:
X.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [21]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [22]:
X_train ,X_test , y_train ,y_test = train_test_split(
    X,y,test_size = 0.3 ,random_state=42
)

In [27]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
y_test_scaled = scaler.transform(X_test)

In [28]:
svc = SVC()
s.fit(X_train_scaled ,y_train)

NameError: name 'scv' is not defined