In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("Concrete_Data_Yeh.csv")

In [4]:
df.head()

,cement,slag,flyash,water,superplasticizer,coarseaggregate,fineaggregate,age,csMPa
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [5]:
df.shape

(1030, 9)

In [6]:
df.sample

<bound method NDFrame.sample of       cement   slag  flyash  water  superplasticizer  coarseaggregate  \
0      540.0    0.0     0.0  162.0               2.5           1040.0
1      540.0    0.0     0.0  162.0               2.5           1055.0
2      332.5  142.5     0.0  228.0               0.0            932.0
3      332.5  142.5     0.0  228.0               0.0            932.0
4      198.6  132.4     0.0  192.0               0.0            978.4
...      ...    ...     ...    ...               ...              ...
1025   276.4  116.0    90.3  179.6               8.9            870.1
1026   322.2    0.0   115.6  196.0              10.4            817.9
1027   148.5  139.4   108.6  192.7               6.1            892.4
1028   159.1  186.7     0.0  175.6              11.3            989.6
1029   260.9  100.5    78.3  200.6               8.6            864.5

      fineaggregate  age  csMPa
0             676.0   28  79.99
1             676.0   28  61.89
2             594.0  270  40.27
3             594.0  365  41.05
4             825.5  360  44.30
...             ...  ...    ...
1025          768.3   28  44.28
1026          813.4   28  31.18
1027          780.0   28  23.70
1028          788.9   28  32.77
1029          761.5   28  32.40

[1030 rows x 9 columns]>

In [7]:
df.isnull().sum()

cement              0
slag                0
flyash              0
water               0
superplasticizer    0
coarseaggregate     0
fineaggregate       0
age                 0
csMPa               0
dtype: int64

In [9]:
x = df.drop("csMPa" , axis=1)
y = df["csMPa"]

In [10]:
x

,cement,slag,flyash,water,superplasticizer,coarseaggregate,fineaggregate,age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360
...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28

In [11]:
y

0       79.99
1       61.89
2       40.27
3       41.05
4       44.30
        ...
1025    44.28
1026    31.18
1027    23.70
1028    32.77
1029    32.40
Name: csMPa, Length: 1030, dtype: float64

In [15]:
from sklearn.model_selection import train_test_split

x_train , x_test , y_train ,y_test = train_test_split(x ,y ,test_size= 0.2 , random_state = 42)

In [19]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_train)

In [20]:
import torch
import torch.nn as nn

In [25]:
x_train_tensor = torch.tensor(x_train_scaled , dtype = torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype = torch.float32).view(-1 ,1)

x_test_tensor = torch.tensor(x_test_scaled , dtype = torch.float32)
y_test_tensor = torch.tensor(y_test.values , dtype = torch.float32).view(-1 , 1)