In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Dry_Bean.csv")

In [13]:
df.sample(10)

,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRation,Eccentricity,ConvexArea,EquivDiameter,Extent,Solidity,roundness,Compactness,ShapeFactor1,ShapeFactor2,ShapeFactor3,ShapeFactor4,Class
13548,41443,754.945,290.022778,182.190565,1.591865,0.778057,41801,229.710397,0.747880,0.991436,0.913756,0.792043,0.006998,0.001699,0.627331,0.998627,DERMASON
8480,43395,769.000,284.958030,194.526111,1.464883,0.730747,43780,235.057929,0.816371,0.991206,0.922140,0.824886,0.006567,0.001875,0.680437,0.996761,SIRA
12327,33816,687.426,252.757001,170.793851,1.479895,0.737155,34229,207.499081,0.789356,0.987934,0.899249,0.820943,0.007474,0.002094,0.673947,0.997371,DERMASON
5697,44049,812.823,322.754498,176.276293,1.830958,0.837679,44699,236.822568,0.817236,0.985458,0.837826,0.733755,0.007327,0.001310,0.538396,0.985780,HOROZ
11598,31003,660.955,257.418961,153.843165,1.673256,0.801767,31354,198.681266,0.735296,0.988805,0.891805,0.771821,0.008303,0.001818,0.595707,0.996770,DERMASON
10837,28047,627.089,236.246481,151.572993,1.558632,0.767049,28352,188.972351,0.702299,0.989242,0.896268,0.799895,0.008423,0.002127,0.639832,0.997262,DERMASON
9519,48525,817.194,291.981539,212.927084,1.371275,0.684249,49068,248.563772,0.745529,0.988934,0.913114,0.851300,0.006017,0.001949,0.724711,0.993778,SIRA
8872,45126,794.998,298.079622,194.954239,1.528972,0.756465,45761,239.700245,0.720840,0.986124,0.897232,0.804148,0.006605,0.001704,0.646655,0.988717,SIRA
6375,52968,924.790,387.708889,174.719387,2.219038,0.892703,53585,259.693959,0.677098,0.988486,0.778282,0.669817,0.007320,0.000909,0.448655,0.995582,HOROZ
8499,43442,782.927,296.883367,186.665964,1.590453,0.777606,43849,235.185187,0.809730,0.990718,0.890589,0.792180,0.006834,0.001660,0.627550,0.998088,SIRA

In [6]:
df.shape

(13611, 17)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13611 entries, 0 to 13610
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Area             13611 non-null  int64
 1   Perimeter        13611 non-null  float64
 2   MajorAxisLength  13611 non-null  float64
 3   MinorAxisLength  13611 non-null  float64
 4   AspectRation     13611 non-null  float64
 5   Eccentricity     13611 non-null  float64
 6   ConvexArea       13611 non-null  int64
 7   EquivDiameter    13611 non-null  float64
 8   Extent           13611 non-null  float64
 9   Solidity         13611 non-null  float64
 10  roundness        13611 non-null  float64
 11  Compactness      13611 non-null  float64
 12  ShapeFactor1     13611 non-null  float64
 13  ShapeFactor2     13611 non-null  float64
 14  ShapeFactor3     13611 non-null  float64
 15  ShapeFactor4     13611 non-null  float64
 16  Class            13611 non-null  object
dtypes: float64(14), int64(2), object(1)
memory usage: 1.8+ MB

In [14]:
x = df.drop("Class" , axis = 1)
y = df["Class"]

In [15]:
x.head()

,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRation,Eccentricity,ConvexArea,EquivDiameter,Extent,Solidity,roundness,Compactness,ShapeFactor1,ShapeFactor2,ShapeFactor3,ShapeFactor4
0,28395,610.291,208.178117,173.888747,1.197191,0.549812,28715,190.141097,0.763923,0.988856,0.958027,0.913358,0.007332,0.003147,0.834222,0.998724
1,28734,638.018,200.524796,182.734419,1.097356,0.411785,29172,191.272751,0.783968,0.984986,0.887034,0.953861,0.006979,0.003564,0.909851,0.998430
2,29380,624.110,212.826130,175.931143,1.209713,0.562727,29690,193.410904,0.778113,0.989559,0.947849,0.908774,0.007244,0.003048,0.825871,0.999066
3,30008,645.884,210.557999,182.516516,1.153638,0.498616,30724,195.467062,0.782681,0.976696,0.903936,0.928329,0.007017,0.003215,0.861794,0.994199
4,30140,620.134,201.847882,190.279279,1.060798,0.333680,30417,195.896503,0.773098,0.990893,0.984877,0.970516,0.006697,0.003665,0.941900,0.999166

In [34]:
df["Class"].unique()

array(['SEKER', 'BARBUNYA', 'BOMBAY', 'CALI', 'HOROZ', 'SIRA', 'DERMASON'],
      dtype=object)

In [18]:
from sklearn.preprocessing import StandardScaler , LabelEncoder
le = LabelEncoder()

y = le.fit_transform(y)

In [19]:
from sklearn.model_selection import train_test_split

x_train ,x_test , y_train , y_test = train_test_split(
    x ,y ,test_size = 0.2 ,random_state = 42
)

In [21]:
x_train.shape

(10888, 16)

In [22]:
scaler =StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

# ANN

In [24]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader , TensorDataset

In [55]:
x_train_tensor = torch.tensor(x_train_scaled ,dtype=torch.float32)
x_test_tensor = torch.tensor(x_test_scaled ,dtype=torch.float32)

y_train_tensor = torch.tensor(y_train ,dtype=torch.long).view(-1)
y_test_tensor = torch.tensor(y_test ,dtype=torch.long).view(-1)

In [56]:
train_dataset = TensorDataset(x_train_tensor ,y_train_tensor)
test_dataset = TensorDataset(x_test_tensor , x_test_tensor)

In [57]:
train_loader = DataLoader(train_dataset ,batch_size = 32 ,shuffle = True )
test_loader = DataLoader(test_dataset ,batch_size = 32)

In [58]:
#model

class ANN(nn.Module):
    def __init__(self):
        super(ANN ,self).__init__()

        self.model = nn.Sequential(
            nn.Linear(x.shape[1],64),
            nn.ReLU() ,

            nn.Linear(64 ,64),
            nn.ReLU() ,

            nn.Linear(64 ,7)
        )

    def forward(self,x):
        return self.model(x)

In [59]:
model = ANN()

# loss and optim
criteria = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())

In [ ]:
epochs = 100 ;

for epoch in range(epochs):
    model.train()
    optimizer.zero_grad()

    running_loss = 0.0 

    for xb ,yb in train_loader:
        optimizer.zero_grad()

        output = model(xb)
        loss = criteria(output , yb)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    train_loss = running_loss/len(train_loader)
    print(f"epoch {epoch} , loss {train_loss}")

epoch 0 , loss 0.5625429269461688
epoch 1 , loss 0.21980660952712325
epoch 2 , loss 0.20869633063805068
epoch 3 , loss 0.20468177805897778
epoch 4 , loss 0.19979168890901675
epoch 5 , loss 0.19747031315112393
epoch 6 , loss 0.1949414429077305
epoch 7 , loss 0.1922400116898622
epoch 8 , loss 0.19199901967257524
epoch 9 , loss 0.18873617209253774
epoch 10 , loss 0.18714329130576154
epoch 11 , loss 0.18679955048907187
epoch 12 , loss 0.18676393686130074
epoch 13 , loss 0.1835153482395533
epoch 14 , loss 0.184304275203092

In [ ]:
# Evaluation

model.eval()

total = 0
correct = 0 

with torch.no_grad():
    for xb , yb in test_loader:
        outputs = model(xb)
        _, predicted = torch.max(outputs , 1)

        correct += (predicted == yb).sum().item()
        total += yb.size(0)\

print("accuracy: ", correct/total * 100)